### ISSUE TITLE
Error !!

### ISSUE THREAD

**Issue by Jucamhc** [EvanZhouDev/bard-ai#36] opened 2023-07-17 16:40 UTC
/bard-ia/node_modules/bard-ai/index.js:29
    else throw new Error("Could not get Google Bard.");
               ^

**Comment by kevindevm** [comment] 2023-07-17 22:09
same

**Comment by ThatXliner** [comment] 2023-07-17 23:42
Duplicate of https://github.com/EvanZhouDev/bard-ai/issues/31

**Comment by Jucamhc** [comment] 2023-07-18 00:22
/node_modules/bard-ai/index.js:29
    else throw new Error("Could not get Google Bard.");
               ^
               
               with version "bard-ai": "^1.5.4", same

**Comment by EvanZhouDev** [comment] 2023-07-18 07:05
I've heard that this may be because your account should be using another cookie... this feature will be implemented in v2. Please hold on...

**Comment by thisago** [comment] 2023-07-20 01:48
Yes, now the needed cookies are: `__Secure-1PSID` and `__Secure-1PSIDTS`

See my working implementation: https://github.com/thisago/bard/blob/master/src/bard.nim#L76

But the `__Secure-1PSIDTS` expires so fast, then I made this lib to workaround this: https://github.com/thisago/gookie

**Comment by EvanZhouDev** [comment] 2023-07-20 02:59
Hmm... looks like they're forcing us to use the PaLM API... time to migrate I guess...

**Comment by thisago** [comment] 2023-07-20 03:06
for what I want. my dirty workaround works well, but for larger projects, an api is better; but migrating to an paid API is very divergent from an open source lib that uses the internal API for free

**Comment by EvanZhouDev** [comment] 2023-07-20 03:08
I know. But the bigger question: How does Google do it (and why can't we do it)?

**Comment by thisago** [comment] 2023-07-20 03:09
do what? didnt understood

**Comment by EvanZhouDev** [comment] 2023-07-23 09:10
Use of `__Secure-1PSIDTS` is coming in version 2... I've heard that if you don't refresh the bard.google.com page, it doesn't change the key, so that might be a solution?

Either way, stay tuned to #30, the Feature Tracker for version 2. I'll be closing this, but feel free to reopen.

**Closed by EvanZhouDev** 2023-07-23 09:10 UTC

**Comment by thisago** [comment] 2023-07-23 18:33
With my tests, with my [cli bard app](https://github.com/thisago/clibard) some times the session expires, but this app can regain with my dirty workaround

**Comment by thisago** [comment] 2023-07-23 18:38
Also, I tested getting the `__Secure-1PSIDTS` cookie, getting `SNlM0e` and refreshing a google bard page in browser and session still works, I think that it expires with time

**Comment by thisago** [comment] 2023-07-23 20:20
I tested by 1 hour and 40 minutes with same session and it didn't expired

**Comment by EvanZhouDev** [comment] 2023-07-24 03:03
There's no way for it to expire on the same session, I don't think. Setting a timer for cookie expiration seems like a bad idea 😅.
